const goWestTiming = {
  0: 'Welcome to 3D karaoke!',
  8: "Safe on the interstate",
  18: "New York is three thousand miles away",
  25: "And I'm not looking forward to following through",
  30: "But it's better than always running back into you",
  35: "I've closed my eyes and my bank account",
  40: "And gone west, young man",
  46: "Take off the parking brake",
  55: "Go coasting into a different state",
  65: "And I'm not looking forward to missing you",
  68: "But I must have something better to do",
  73: "I've got to tear my life apart",
  78: "And go west, young man",
  85: "And it feels like I've got something to prove",
  87: "But in some ways it's just something to do",
  91: "My friends turn me around and say,",
  97: "You go west, young man.",
  107: "Stepping down off my platform shoes",
  119: "Sixty-nine in the afternoon",
  125: "And I'm waiting for someone in the know",
  130: "Like Pirner tells me on the radio",
  135: "Says Take it from someone who's been there before,",
  140: "You go west, young man.",
  143: "And I'm looking for somebody to do my thinking for me",
  150: "Till I come through",
  153: "The state-line highway sign says,",
  159: "You have gone west, young man.",
  167: "And it feels like I've got something to prove",
  171: "But in some ways it's just something to do",
  176: "The state-line highway sign says,",
  180: "You have gone west, young man."
}
